# Generated by Django 3.2.9 on 2021-12-14 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drops', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_offer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_offer', to='drops.drop', verbose_name='Drop'),
        ),
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_offer', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
