# docker-compose.yml

version: "3.7"

services:

  postgres_2:
    container_name: postgres_2
    hostname: postgres_2
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - project_config/.env.postgres
    networks:
      - second
    ports:
      - "5433:5432"
    restart: always

  pgbackups_2:
    container_name: pgbackups_2
    hostname: pgbackups_2
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./backups:/backups
    links:
      - postgres_2
    depends_on:
      - postgres_2
    env_file:
      - project_config/.env.postgres
    networks:
      - second

  web_2:
    build: GraphiteBack
    container_name: web_2
    ports:
      - "8001:8001"
    command: sh -c "python manage.py makemigrations&& python manage.py migrate&& gunicorn config.asgi:application --bind 0.0.0.0:8001 -w 3 -k uvicorn.workers.UvicornWorker --log-file -"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - project_config/.env.back
    hostname: web_2
    image: web-image
    networks:
      - second
    depends_on:
      - postgres_2
    restart: always

  nginx_2:
    container_name: nginx_2
    image: nginx:alpine
    hostname: nginx_2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "4000:4000"
    depends_on:
      - web_2
    networks:
      - second
    restart: always

networks:
  second:
    name: second
#    external: true
#    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
