# Generated by Django 3.2.9 on 2021-12-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops', '0001_initial'),
        ('drops_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcollectiondrop',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_collection_drop', to='drops_collections.specialcollection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='specialcollectiondrop',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_collection_drop', to='drops.drop', verbose_name='Drop'),
        ),
        migrations.AddField(
            model_name='dropview',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_view', to='drops.drop', verbose_name='Drop'),
        ),
    ]
