# Generated by Django 3.2.9 on 2021-12-14 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='all_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='All count'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='auction_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Auction deadline'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='in_stock',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='init_cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Init cost'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='min_rate',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min rate'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='sell_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sell count'),
        ),
    ]
