# Generated by Django 3.2.9 on 2021-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='color',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Color'),
        ),
    ]
