# Generated by Django 3.2.9 on 2021-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0004_drop_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Color'),
        ),
    ]
