# Generated by Django 3.2.9 on 2021-12-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('picture_big', models.ImageField(blank=True, null=True, upload_to='drop/picture_big', verbose_name='Big picture')),
                ('picture_small', models.ImageField(blank=True, null=True, upload_to='drop/picture_small', verbose_name='Small picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection Like',
                'verbose_name_plural': 'Collections Likes',
            },
        ),
        migrations.CreateModel(
            name='CollectionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection subscription',
                'verbose_name_plural': 'Collections subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SpecialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('drops', models.ManyToManyField(related_name='special_collection', through='drops.SpecialCollectionDrop', to='drops.Drop', verbose_name='Drop')),
            ],
            options={
                'verbose_name': 'Special collection',
                'verbose_name_plural': 'Special collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_view', to='drops_collections.collection', verbose_name='Collection')),
            ],
            options={
                'verbose_name': 'Collection view',
                'verbose_name_plural': 'Collections views',
            },
        ),
    ]
