# Generated by Django 3.2.9 on 2021-12-14 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_view', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='collectionsubscription',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_subscription', to='drops_collections.collection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='collectionsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_subscription', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='collectionlike',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_like', to='drops_collections.collection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='collectionlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddConstraint(
            model_name='collectionview',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='unique_collection_view'),
        ),
        migrations.AddConstraint(
            model_name='collectionsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='unique_collection_subscription'),
        ),
        migrations.AddConstraint(
            model_name='collectionlike',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='unique_collection_like'),
        ),
    ]
