# Generated by Django 3.2.9 on 2021-12-15 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drops', '0004_auto_20211214_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_cost', models.FloatField(verbose_name='Init cost')),
                ('current_cost', models.FloatField(verbose_name='Init cost')),
                ('min_rate', models.FloatField(verbose_name='Min rate')),
                ('sell_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sell count')),
                ('auction_deadline', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Auction deadline')),
                ('royalty', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Royalty')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_current_user', to=settings.AUTH_USER_MODEL, verbose_name='Current user')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='drops.drop', verbose_name='Drop')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.CreateModel(
            name='AuctionUserBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bit')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_user_bid', to='auction.auction', verbose_name='Auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_user_bid', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Auction user bit',
                'verbose_name_plural': 'Auction users bids',
            },
        ),
    ]
