# Generated by Django 3.2.9 on 2021-12-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drops', '0002_initial'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuserbid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_user_bid', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_current_user', to=settings.AUTH_USER_MODEL, verbose_name='Current user'),
        ),
        migrations.AddField(
            model_name='auction',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='drops.drop', verbose_name='Drop'),
        ),
    ]
