# Generated by Django 3.2.9 on 2021-11-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondrop',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_drop', to='api.drop'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='init_cost',
            field=models.FloatField(default=0, verbose_name='Init cost'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='min_rate',
            field=models.FloatField(default=0, verbose_name='Min rate'),
        ),
    ]
