# Generated by Django 3.2.9 on 2021-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
        ('users', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auction_bids',
            field=models.ManyToManyField(related_name='bids', through='auction.AuctionUserBit', to='auction.Auction', verbose_name='Auction bids'),
        ),
    ]
