# Generated by Django 3.2.9 on 2021-12-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20211215_1338'),
        ('users', '0004_user_auction_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auction_bids',
            field=models.ManyToManyField(related_name='bids', through='auction.AuctionUserBid', to='auction.Auction', verbose_name='Auction bids'),
        ),
    ]
