name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@API-V1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@API-V1
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "/home/extralait/apps/graphiteV1"

    - name: Executing remote command
      uses: appleboy/ssh-action@API-V1
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: cd apps/graphiteV1/&&ls
        
    - name: Rebuild command
      uses: appleboy/ssh-action@API-V1
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script:  cd apps/graphiteV1/&&docker build -t web-image ./GraphiteBack


    - name: Rebuild command
      uses: appleboy/ssh-action@API-V1
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script:  cd apps/graphiteV1/&&docker-compose up -d
